# Generated by Django 5.2.6 on 2025-09-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomelivro', models.CharField(max_length=100)),
                ('datalivro', models.CharField(max_length=100)),
                ('autorlivro', models.CharField(max_length=100)),
                ('descricaolivro', models.CharField(max_length=100)),
            ],
        ),
    ]
