# Generated by Django 5.2.6 on 2025-09-12 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='autorlivro',
            new_name='autor',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='datalivro',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='descricaolivro',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='livros',
            old_name='nomelivro',
            new_name='titulo',
        ),
    ]
