# Generated by Django 5.2.6 on 2025-09-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_rename_categoria_categoria_nome_livros_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
